ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/graphs/contributors"><img src="https://img.shields.io/github/contributors/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/network/members"><img src="https://img.shields.io/github/forks/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/stargazers"><img src="https://img.shields.io/github/stars/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues"><img src="https://img.shields.io/github/issues/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge" alt="Issues"></a>
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/blob/master/LICENSE"><img src="https://img.shields.io/github/license/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge" alt="License"></a>
<br />
<h3 align="center">Markdown/AsciiDoc to Google Docs Converter</h3>
<p align="center">
A Google Apps Script that converts selected Markdown or AsciiDoc formatted text in Google Docs to native Google Docs formatting.<br />
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues">Report Bug</a>
&middot;
<a href="https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge[Contributors,link=https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/graphs/contributors]
image:https://img.shields.io/github/forks/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge[Forks,link=https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/network/members]
image:https://img.shields.io/github/stars/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge[Stars,link=https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/stargazers]
image:https://img.shields.io/github/issues/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge[Issues,link=https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues]
image:https://img.shields.io/github/license/AMDphreak/google-docs-asciidoc-markdown-converter.svg?style=for-the-badge[License,link=https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/blob/master/LICENSE]

= Markdown/AsciiDoc to Google Docs Converter

A Google Apps Script that converts selected Markdown or AsciiDoc formatted text in Google Docs to native Google Docs formatting.

link:https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues[Report Bug] ·
link:https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter/issues[Request Feature]
endif::[]


== About The Project

A Google Apps Script that converts selected Markdown or AsciiDoc formatted text in Google Docs to native Google Docs formatting.

link:#readme-top[back to top]

== Features

* Automatically detects Markdown or AsciiDoc format
* Converts headers, bold, italic, code blocks, and links
* Appears in the Extensions menu
* Works with selected text in Google Docs

link:#readme-top[back to top]

== Installation

=== Manual Installation

1. Open a Google Docs document
2. Go to Extensions → Apps Script
3. Create a new project
4. Copy the contents of `Code.gs` into the script editor
5. Copy the contents of `appsscript.json` into the project settings (or configure manually)
6. Save the project
7. Reload the Google Docs document
8. The "Markdown/AsciiDoc Converter" menu will appear in the Extensions menu

=== Automated Installation with CI/CD

For automated deployment using GitHub Actions, see `CI_CD_GUIDE.adoc` for complete setup instructions. This allows you to automatically push code changes to Apps Script when you push to your repository.

link:#readme-top[back to top]

== Usage

1. Select the text you want to convert in your Google Docs document
2. Go to Extensions → Markdown/AsciiDoc Converter → Convert Selected Text
3. The script will automatically detect whether the text is Markdown or AsciiDoc and convert it accordingly

=== Supported Formatting

==== Markdown

* Headers: `# Header 1` through `###### Header 6`
* Bold: `**bold text**` or `__bold text__`
* Italic: `*italic text*` or `_italic text_`
* Code: `` `code` ``
* Links: `[link text](url)`

==== AsciiDoc

* Headers: `= Header 1` through `====== Header 6`
* Bold: `**bold text**`
* Italic: `*italic text*`
* Code: `` `code` `` or ````code````
* Links: `link:url[text]` or `url[text]`

=== Files

* `Code.gs` - Main script file containing all conversion logic
* `appsscript.json` - Apps Script project configuration

=== Documentation

* `README.adoc` - This file, basic usage and installation
* `CI_CD_GUIDE.adoc` - Guide for setting up automated deployment with GitHub Actions
* `PUBLISHING_GUIDE.adoc` - Complete guide for publishing to Google Workspace Marketplace

link:#readme-top[back to top]

== License

MIT License

link:#readme-top[back to top]

== Contact

Ryan Johnson — link:https://twitter.com/amdphreak[@amdphreak]

* Project: https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter
* Site: https://ryanjohnson.dev

link:#readme-top[back to top]
